# Generated by Django 5.2.1 on 2025-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='exict', max_length=15),
            preserve_default=False,
        ),
    ]
